# Generated by Django 5.1.5 on 2025-03-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='test',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
