# Generated by Django 5.1.5 on 2025-02-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_alter_invoice_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedInvoiceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(blank=True, max_length=20, null=True)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("invoice_number", models.CharField(max_length=100)),
                ("fiscal_year", models.CharField(blank=True, max_length=10, null=True)),
                ("client", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "amount_pre_tax",
                    models.DecimalField(decimal_places=2, max_digits=15, null=True),
                ),
                (
                    "vat_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, max_digits=15, null=True),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, max_digits=15, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("period", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed_data",
                        to="data.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-invoice_date"],
                "indexes": [
                    models.Index(
                        fields=["invoice_number"], name="data_proces_invoice_d5532d_idx"
                    ),
                    models.Index(
                        fields=["client"], name="data_proces_client_961274_idx"
                    ),
                    models.Index(
                        fields=["invoice_date"], name="data_proces_invoice_fb64a7_idx"
                    ),
                ],
            },
        ),
    ]
