# Generated by Django 5.1.5 on 2025-03-17 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_anomaly_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomaly',
            name='test',
        ),
    ]
