# Generated by Django 5.1.5 on 2025-03-03 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_processedinvoicedata'),
        ('data', 'create_facturation_manuelle'),
    ]

    operations = [
    ]
