# Generated by Django 5.1.5 on 2025-03-08 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_invoice_anomalies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('missing_data', 'Missing Data'), ('duplicate_data', 'Duplicate Data'), ('invalid_data', 'Invalid Data'), ('outlier', 'Outlier'), ('inconsistent_data', 'Inconsistent Data'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies_related', to='data.invoice')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='data_anomal_type_2a7e34_idx'), models.Index(fields=['status'], name='data_anomal_status_b0cd85_idx'), models.Index(fields=['created_at'], name='data_anomal_created_a2f092_idx')],
            },
        ),
    ]
