# Generated by Django 5.1.5 on 2025-03-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_facturationmanuelle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturationmanuelle',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
