# Generated by Django 5.1.5 on 2025-03-03 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_merge_20250303_0309'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facturationmanuelle',
            new_name='data_factur_invoice_f0f9a1_idx',
            old_name='data_factura_invoice_d0a4d0_idx',
        ),
        migrations.RenameIndex(
            model_name='facturationmanuelle',
            new_name='data_factur_fiscal__b66755_idx',
            old_name='data_factura_fiscal__1a9d30_idx',
        ),
        migrations.RenameIndex(
            model_name='facturationmanuelle',
            new_name='data_factur_departm_400c2b_idx',
            old_name='data_factura_departm_f8c1b9_idx',
        ),
        migrations.RenameIndex(
            model_name='facturationmanuelle',
            new_name='data_factur_invoice_363ff7_idx',
            old_name='data_factura_invoice_e1c1a9_idx',
        ),
    ]
