# Generated by Django 5.1.5 on 2025-03-08 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_anomaly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='anomalies',
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='data.invoice'),
        ),
    ]
