# Generated by Django 5.1.5 on 2025-03-03 03:55

from django.db import migrations


class Migration(migrations.Migration):
    """
    This is a merge migration that combines two branches:
    - 0002_facturation_manuelle
    - 0005_rename_data_factura_invoice_d0a4d0_idx_data_factur_invoice_f0f9a1_idx_and_more

    Since both branches create the FacturationManuelle model, we need to handle this conflict.
    """

    dependencies = [
        ('data', '0002_facturation_manuelle'),
        ('data', '0005_rename_data_factura_invoice_d0a4d0_idx_data_factur_invoice_f0f9a1_idx_and_more'),
    ]

    operations = [
        # No operations needed as this is just a merge migration
        # The FacturationManuelle model already exists in the database
    ]
