# Generated by Django 5.1.5 on 2025-03-08 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_invoice_anomalies_alter_anomaly_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_anomalies', to='data.invoice'),
        ),
        migrations.AddIndex(
            model_name='facturationmanuelle',
            index=models.Index(fields=['invoice_date'], name='data_factur_invoice_9e7310_idx'),
        ),
    ]
