# Generated by Django 5.1.5 on 2025-03-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_facturationmanuelle_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturationmanuelle',
            options={'ordering': ['-invoice_date']},
        ),
        migrations.AddField(
            model_name='facturationmanuelle',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facturationmanuelle',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturationmanuelle',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facturationmanuelle',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facturationmanuelle',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facturationmanuelle',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='facturationmanuelle',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddIndex(
            model_name='facturationmanuelle',
            index=models.Index(fields=['invoice_number'], name='data_factur_invoice_363ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='facturationmanuelle',
            index=models.Index(fields=['invoice_date'], name='data_factur_invoice_9e7310_idx'),
        ),
    ]
