# Generated by Django 5.1.5 on 2025-03-08 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_collectionobjective_revenueobjective'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGBSSCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_type', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('client_code', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('collection_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('is_previous_year', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngbss_collection_data', to='data.invoice')),
            ],
            options={
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['dot'], name='data_ngbssc_dot_038002_idx'), models.Index(fields=['invoice_number'], name='data_ngbssc_invoice_398837_idx'), models.Index(fields=['payment_date'], name='data_ngbssc_payment_217dbe_idx'), models.Index(fields=['year'], name='data_ngbssc_year_558bd2_idx'), models.Index(fields=['month'], name='data_ngbssc_month_81ea02_idx'), models.Index(fields=['is_previous_year'], name='data_ngbssc_is_prev_bc70d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnfinishedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_type', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('client_code', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('days_pending', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unfinished_invoice_data', to='data.invoice')),
            ],
            options={
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['dot'], name='data_unfini_dot_074bc3_idx'), models.Index(fields=['invoice_number'], name='data_unfini_invoice_142ade_idx'), models.Index(fields=['invoice_date'], name='data_unfini_invoice_6ea01f_idx'), models.Index(fields=['status'], name='data_unfini_status_fb59fe_idx'), models.Index(fields=['days_pending'], name='data_unfini_days_pe_602668_idx')],
            },
        ),
    ]
