# Generated by Django 5.1.5 on 2025-03-04 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(upload_to='invoices/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('preview', 'Preview'), ('saved', 'Saved to Database'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='FacturationManuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('fiscal_year', models.CharField(blank=True, max_length=10, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_pre_tax', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vat_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturation_manuelle_data', to='data.invoice')),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedInvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('fiscal_year', models.CharField(blank=True, max_length=10, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_pre_tax', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vat_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_data', to='data.invoice')),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='data_invoic_invoice_c3a46d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='data_invoic_status_9df842_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['upload_date'], name='data_invoic_upload__9afc6e_idx'),
        ),
        migrations.AddIndex(
            model_name='facturationmanuelle',
            index=models.Index(fields=['invoice'], name='data_factur_invoice_f0f9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='facturationmanuelle',
            index=models.Index(fields=['fiscal_year'], name='data_factur_fiscal__b66755_idx'),
        ),
        migrations.AddIndex(
            model_name='facturationmanuelle',
            index=models.Index(fields=['department'], name='data_factur_departm_400c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='facturationmanuelle',
            index=models.Index(fields=['invoice_number'], name='data_factur_invoice_363ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='processedinvoicedata',
            index=models.Index(fields=['invoice_number'], name='data_proces_invoice_d5532d_idx'),
        ),
        migrations.AddIndex(
            model_name='processedinvoicedata',
            index=models.Index(fields=['client'], name='data_proces_client_961274_idx'),
        ),
        migrations.AddIndex(
            model_name='processedinvoicedata',
            index=models.Index(fields=['invoice_date'], name='data_proces_invoice_fb64a7_idx'),
        ),
    ]
