# Generated by Django 5.1.5 on 2025-03-04 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CACNT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_adjusted', models.CharField(blank=True, max_length=50, null=True)),
                ('pri_identity', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('amount_pre_tax', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('actel', models.CharField(blank=True, max_length=100, null=True)),
                ('dot', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_lev1', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_lev2', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_lev3', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='CADNT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pri_identity', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=20, null=True)),
                ('ext_trans_type', models.CharField(blank=True, max_length=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('amount_pre_tax', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('actel', models.CharField(blank=True, max_length=100, null=True)),
                ('dot', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_lev1', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_lev2', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_lev3', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='CANonPeriodique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_pre_tax', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('sale_type', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CAPeriodique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_pre_tax', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CARFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('actel', models.CharField(blank=True, max_length=100, null=True)),
                ('dot', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('droit_timbre', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('amount_pre_tax', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pri_identity', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_lev1', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_lev2', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_lev3', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='CreancesNGBSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot', models.CharField(blank=True, max_length=50, null=True)),
                ('actel', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('subscriber_status', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_lev1', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_lev2', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_lev3', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('open_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('invoice_amount_ht', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('dispute_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('dispute_tax_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('dispute_net_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('creance_brut', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('creance_net', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('creance_ht', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EtatFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_type', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_object', models.TextField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('terminated_flag', models.CharField(blank=True, max_length=5, null=True)),
                ('amount_pre_tax', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('revenue_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('collection_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('invoice_credit_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalVentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_type', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('invoice_object', models.TextField(blank=True, null=True)),
                ('account_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gl_date', models.DateField(blank=True, null=True)),
                ('billing_period', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('terminated_flag', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('revenue_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='ParcCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actel_code', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_l1_code', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_l1_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_l2_code', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_l2_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_l3_code', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_l3_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('telecom_type', models.CharField(blank=True, max_length=50, null=True)),
                ('offer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('offer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subscriber_status', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='detection_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['file_type'], name='data_invoic_file_ty_a22e09_idx'),
        ),
        migrations.AddField(
            model_name='cacnt',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_cnt_data', to='data.invoice'),
        ),
        migrations.AddField(
            model_name='cadnt',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_dnt_data', to='data.invoice'),
        ),
        migrations.AddField(
            model_name='canonperiodique',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_non_periodique_data', to='data.invoice'),
        ),
        migrations.AddField(
            model_name='caperiodique',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_periodique_data', to='data.invoice'),
        ),
        migrations.AddField(
            model_name='carfd',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_rfd_data', to='data.invoice'),
        ),
        migrations.AddField(
            model_name='creancesngbss',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creances_ngbss_data', to='data.invoice'),
        ),
        migrations.AddField(
            model_name='etatfacture',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etat_facture_data', to='data.invoice'),
        ),
        migrations.AddField(
            model_name='journalventes',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_ventes_data', to='data.invoice'),
        ),
        migrations.AddField(
            model_name='parccorporate',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parc_corporate_data', to='data.invoice'),
        ),
        migrations.AddIndex(
            model_name='cacnt',
            index=models.Index(fields=['invoice'], name='data_cacnt_invoice_a0d77c_idx'),
        ),
        migrations.AddIndex(
            model_name='cacnt',
            index=models.Index(fields=['dot'], name='data_cacnt_dot_d4bad6_idx'),
        ),
        migrations.AddIndex(
            model_name='cacnt',
            index=models.Index(fields=['transaction_id'], name='data_cacnt_transac_126d08_idx'),
        ),
        migrations.AddIndex(
            model_name='cacnt',
            index=models.Index(fields=['department'], name='data_cacnt_departm_d3a269_idx'),
        ),
        migrations.AddIndex(
            model_name='cadnt',
            index=models.Index(fields=['invoice'], name='data_cadnt_invoice_06a437_idx'),
        ),
        migrations.AddIndex(
            model_name='cadnt',
            index=models.Index(fields=['dot'], name='data_cadnt_dot_73a796_idx'),
        ),
        migrations.AddIndex(
            model_name='cadnt',
            index=models.Index(fields=['transaction_id'], name='data_cadnt_transac_e503c4_idx'),
        ),
        migrations.AddIndex(
            model_name='cadnt',
            index=models.Index(fields=['department'], name='data_cadnt_departm_bdff2c_idx'),
        ),
        migrations.AddIndex(
            model_name='canonperiodique',
            index=models.Index(fields=['invoice'], name='data_canonp_invoice_af8672_idx'),
        ),
        migrations.AddIndex(
            model_name='canonperiodique',
            index=models.Index(fields=['dot'], name='data_canonp_dot_490f58_idx'),
        ),
        migrations.AddIndex(
            model_name='canonperiodique',
            index=models.Index(fields=['product'], name='data_canonp_product_08e123_idx'),
        ),
        migrations.AddIndex(
            model_name='canonperiodique',
            index=models.Index(fields=['channel'], name='data_canonp_channel_7d48d0_idx'),
        ),
        migrations.AddIndex(
            model_name='caperiodique',
            index=models.Index(fields=['invoice'], name='data_caperi_invoice_fbdd40_idx'),
        ),
        migrations.AddIndex(
            model_name='caperiodique',
            index=models.Index(fields=['dot'], name='data_caperi_dot_b0e952_idx'),
        ),
        migrations.AddIndex(
            model_name='caperiodique',
            index=models.Index(fields=['product'], name='data_caperi_product_34f881_idx'),
        ),
        migrations.AddIndex(
            model_name='carfd',
            index=models.Index(fields=['invoice'], name='data_carfd_invoice_f52548_idx'),
        ),
        migrations.AddIndex(
            model_name='carfd',
            index=models.Index(fields=['dot'], name='data_carfd_dot_900a83_idx'),
        ),
        migrations.AddIndex(
            model_name='carfd',
            index=models.Index(fields=['transaction_id'], name='data_carfd_transac_ff5a12_idx'),
        ),
        migrations.AddIndex(
            model_name='carfd',
            index=models.Index(fields=['department'], name='data_carfd_departm_27e01a_idx'),
        ),
        migrations.AddIndex(
            model_name='creancesngbss',
            index=models.Index(fields=['invoice'], name='data_creanc_invoice_b97887_idx'),
        ),
        migrations.AddIndex(
            model_name='creancesngbss',
            index=models.Index(fields=['dot'], name='data_creanc_dot_aa4313_idx'),
        ),
        migrations.AddIndex(
            model_name='creancesngbss',
            index=models.Index(fields=['product'], name='data_creanc_product_6abf1c_idx'),
        ),
        migrations.AddIndex(
            model_name='creancesngbss',
            index=models.Index(fields=['year'], name='data_creanc_year_6c4627_idx'),
        ),
        migrations.AddIndex(
            model_name='creancesngbss',
            index=models.Index(fields=['customer_lev1'], name='data_creanc_custome_026865_idx'),
        ),
        migrations.AddIndex(
            model_name='etatfacture',
            index=models.Index(fields=['invoice'], name='data_etatfa_invoice_6ca2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='etatfacture',
            index=models.Index(fields=['organization'], name='data_etatfa_organiz_16a32c_idx'),
        ),
        migrations.AddIndex(
            model_name='etatfacture',
            index=models.Index(fields=['invoice_number'], name='data_etatfa_invoice_40bc11_idx'),
        ),
        migrations.AddIndex(
            model_name='etatfacture',
            index=models.Index(fields=['payment_date'], name='data_etatfa_payment_458273_idx'),
        ),
        migrations.AddIndex(
            model_name='journalventes',
            index=models.Index(fields=['invoice'], name='data_journa_invoice_4983c3_idx'),
        ),
        migrations.AddIndex(
            model_name='journalventes',
            index=models.Index(fields=['organization'], name='data_journa_organiz_9852c4_idx'),
        ),
        migrations.AddIndex(
            model_name='journalventes',
            index=models.Index(fields=['invoice_number'], name='data_journa_invoice_3bc968_idx'),
        ),
        migrations.AddIndex(
            model_name='journalventes',
            index=models.Index(fields=['gl_date'], name='data_journa_gl_date_ce3a88_idx'),
        ),
        migrations.AddIndex(
            model_name='parccorporate',
            index=models.Index(fields=['invoice'], name='data_parcco_invoice_a20ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='parccorporate',
            index=models.Index(fields=['telecom_type'], name='data_parcco_telecom_868a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='parccorporate',
            index=models.Index(fields=['offer_type'], name='data_parcco_offer_t_16b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='parccorporate',
            index=models.Index(fields=['state'], name='data_parcco_state_5f91d5_idx'),
        ),
        migrations.AddIndex(
            model_name='parccorporate',
            index=models.Index(fields=['subscriber_status'], name='data_parcco_subscri_a43d20_idx'),
        ),
    ]
