# Generated by Django 5.1.5 on 2025-03-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_cacnt_cadnt_canonperiodique_caperiodique_carfd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='anomalies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
