# Generated by Django 5.1.5 on 2025-03-08 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_anomaly_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('upload', 'File Upload'), ('process', 'Data Processing'), ('save', 'Data Saving'), ('export', 'Data Export'), ('other', 'Other Operation')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('current_item', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('estimated_completion_time', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_trackers', to='data.invoice')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['invoice'], name='data_progre_invoice_24308d_idx'), models.Index(fields=['operation_type'], name='data_progre_operati_dedfc4_idx'), models.Index(fields=['status'], name='data_progre_status_38fa12_idx')],
            },
        ),
    ]
