# Generated by Django 5.1.5 on 2025-03-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_progresstracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dot'], name='data_collec_dot_47c99c_idx'), models.Index(fields=['year'], name='data_collec_year_b479e2_idx'), models.Index(fields=['month'], name='data_collec_month_441b1a_idx')],
                'unique_together': {('dot', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='RevenueObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dot'], name='data_revenu_dot_d9b99e_idx'), models.Index(fields=['year'], name='data_revenu_year_c86a41_idx'), models.Index(fields=['month'], name='data_revenu_month_4fa3d8_idx')],
                'unique_together': {('dot', 'year', 'month')},
            },
        ),
    ]
