# Generated by Django 5.1.5 on 2025-02-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_role_and_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_email_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_date_joined_idx',
        ),
    ]
