# Generated by Django 5.1.5 on 2025-03-07 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_users_email_role_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDOTPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot_code', models.CharField(max_length=50)),
                ('dot_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dot_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'dot_code'], name='users_userd_user_id_e85a3e_idx')],
                'unique_together': {('user', 'dot_code')},
            },
        ),
    ]
